### ISSUE TITLE
[Feature request] Option to diminish the brightness in "item based" mode

### ISSUE THREAD

**Issue by 0x5c** [Bernasss12/Colored-Tooltips-Fabric#1]
In item-based mode, the colours can get pretty bright (pure white for normal items, etc). I would be great to be able to apply a reduction in brightness, for example reducing it to 50%. That way the border would still remain subtle like vanilla tooltips.

**Comment by Bernasss12** [comment]
Ok I will try to revamp the settings as a whole but I will make sure to add this.
