### ISSUE TITLE
Incompatable with Architectury API

### ISSUE THREAD

**Issue by omoflop** [Bernasss12/Colored-Tooltips-Fabric#2]
Crash report: https://pastebin.com/FEPgREjp

Architectury API seems to conflict with the mixin which this mod uses. I have tried running the game with and without Sodium, as well as any other mods that came up in the stack trace.

**Comment by Bernasss12** [comment]
Thanks for the report, I've looked into it and try to work around it! For now you will have to just not use this mod when using Architectury unfortunately...

**Comment by Bernasss12** [comment]
Fixed in 830dd96e4e490f7bd40defabda9a189f9c9677f8
