### ISSUE TITLE
Mod renames Redstone to "Name based colors"

### ISSUE THREAD

**Issue by CodeF53** [Bernasss12/Colored-Tooltips-Fabric#5]
With mod enabled:
![image](https://user-images.githubusercontent.com/37855219/113064687-bc850480-9174-11eb-837e-01a0097866ca.png)

Without mod enabled:
![image](https://user-images.githubusercontent.com/37855219/113064801-f9e99200-9174-11eb-9ecb-25a03e8ab8c0.png)

**Comment by Bernasss12** [comment]
Can you tell me which version you are using? I do know that I did rename Redstone Dust to take screenshots but I had no idea it had slipped into a production build.
Version 1.1.0 doesn't seem to have that happening on my end can you confirm?

**Comment by CodeF53** [comment]
This occurred on v.1.0.0, let me quickly check if it happens in v1.1.0

**Comment by CodeF53** [comment]
Your Modrinth page still has v1.0.0 as the latest release. :/
https://modrinth.com/mod/colored-tooltips-fabric

**Comment by Bernasss12** [comment]
Oh damn, my bad I do everything manually and I completely forgot

**Comment by CodeF53** [comment]
![image](https://user-images.githubusercontent.com/37855219/113067555-c52c0980-9179-11eb-9ad3-f39b90e60569.png)
Alright, it was just a problem with v1.0.0

**Comment by Bernasss12** [comment]
Yeah I just uploaded the latest version to Modrinth too since it does add more customizability.
