### ISSUE TITLE
Code of colors?

### ISSUE THREAD

**Issue by DuozLOL** [Bernasss12/Colored-Tooltips-Fabric#6]
what color code does the mod use? for example RGB.

**Comment by Bernasss12** [comment]
The mod uses ARGB colors

**Comment by DuozLOL** [comment]
> ARGB

could you recommend a color picker?

**Comment by Bernasss12** [comment]
If you search Google for color picker it will give you a very simple one, but it does not have the 'a' from ARGB, honestly I personally do not know of any color picker that does.
You can use the color picker to get the #rrggbb value and just add two hexadecimal digits for the alpha value
